apiVersion: v1
kind: ConfigMap
metadata:
  name: coworking-map
data:
  DB_NAME: project3DB
  DB_USER: huynt42
  DB_HOST: postgresql-65994ccb46-sb8tb
  DB_PORT: '5432'
---
apiVersion: v1
kind: Secret
metadata:
  name: mypassword
type: Opaque
data:
  DB_PASSWORD: YTEyMw==